/* Auto-generated by genmsg_cpp for file /home/diego/fuerte_workspace/sandbox/Cognitive/world/srv/check_goal_position.srv */
#ifndef WORLD_SERVICE_CHECK_GOAL_POSITION_H
#define WORLD_SERVICE_CHECK_GOAL_POSITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace world
{
template <class ContainerAllocator>
struct check_goal_positionRequest_ {
  typedef check_goal_positionRequest_<ContainerAllocator> Type;

  check_goal_positionRequest_()
  {
  }

  check_goal_positionRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::world::check_goal_positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world::check_goal_positionRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct check_goal_positionRequest
typedef  ::world::check_goal_positionRequest_<std::allocator<void> > check_goal_positionRequest;

typedef boost::shared_ptr< ::world::check_goal_positionRequest> check_goal_positionRequestPtr;
typedef boost::shared_ptr< ::world::check_goal_positionRequest const> check_goal_positionRequestConstPtr;


template <class ContainerAllocator>
struct check_goal_positionResponse_ {
  typedef check_goal_positionResponse_<ContainerAllocator> Type;

  check_goal_positionResponse_()
  : state(false)
  {
  }

  check_goal_positionResponse_(const ContainerAllocator& _alloc)
  : state(false)
  {
  }

  typedef uint8_t _state_type;
  uint8_t state;


  typedef boost::shared_ptr< ::world::check_goal_positionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world::check_goal_positionResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct check_goal_positionResponse
typedef  ::world::check_goal_positionResponse_<std::allocator<void> > check_goal_positionResponse;

typedef boost::shared_ptr< ::world::check_goal_positionResponse> check_goal_positionResponsePtr;
typedef boost::shared_ptr< ::world::check_goal_positionResponse const> check_goal_positionResponseConstPtr;

struct check_goal_position
{

typedef check_goal_positionRequest Request;
typedef check_goal_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct check_goal_position
} // namespace world

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::world::check_goal_positionRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::world::check_goal_positionRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::world::check_goal_positionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::world::check_goal_positionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::world::check_goal_positionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "world/check_goal_positionRequest";
  }

  static const char* value(const  ::world::check_goal_positionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::world::check_goal_positionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::world::check_goal_positionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::world::check_goal_positionRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::world::check_goal_positionResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::world::check_goal_positionResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::world::check_goal_positionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const  ::world::check_goal_positionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::world::check_goal_positionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "world/check_goal_positionResponse";
  }

  static const char* value(const  ::world::check_goal_positionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::world::check_goal_positionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool state\n\
\n\
\n\
";
  }

  static const char* value(const  ::world::check_goal_positionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::world::check_goal_positionResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::world::check_goal_positionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct check_goal_positionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::world::check_goal_positionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct check_goal_positionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<world::check_goal_position> {
  static const char* value() 
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const world::check_goal_position&) { return value(); } 
};

template<>
struct DataType<world::check_goal_position> {
  static const char* value() 
  {
    return "world/check_goal_position";
  }

  static const char* value(const world::check_goal_position&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<world::check_goal_positionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const world::check_goal_positionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<world::check_goal_positionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "world/check_goal_position";
  }

  static const char* value(const world::check_goal_positionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<world::check_goal_positionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const world::check_goal_positionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<world::check_goal_positionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "world/check_goal_position";
  }

  static const char* value(const world::check_goal_positionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_SERVICE_CHECK_GOAL_POSITION_H

