"""autogenerated by genpy from ros_tum_msgs/Dialogue.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_tum_msgs.msg

class Dialogue(genpy.Message):
  _md5sum = "a9200d1c97aa544a016448524d493c40"
  _type = "ros_tum_msgs/Dialogue"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Dialogue ID in the form of UUID
string id

#Dialogue source
string source

#Dialogue destination
string destination

#Dialogue Category
int32 category

#Dialogue Purpose
int32 purpose

#Dialogue Blocking
bool blocking

#Dialogue Message
DialogueMessage message

#Dialogue Expected Reply Type
int32 replyType

#Dialogue ReplyTo UUID
string replyTo

#Dialogue default Modlaities
int32[] defaultModalities

#Dialogue Preferred Modalities
int32[] preferredModalitiey


================================================================================
MSG: ros_tum_msgs/DialogueMessage
#Dialogue Message
string message

int32 messagePurpose


"""
  __slots__ = ['id','source','destination','category','purpose','blocking','message','replyType','replyTo','defaultModalities','preferredModalitiey']
  _slot_types = ['string','string','string','int32','int32','bool','ros_tum_msgs/DialogueMessage','int32','string','int32[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,source,destination,category,purpose,blocking,message,replyType,replyTo,defaultModalities,preferredModalitiey

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Dialogue, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = ''
      if self.source is None:
        self.source = ''
      if self.destination is None:
        self.destination = ''
      if self.category is None:
        self.category = 0
      if self.purpose is None:
        self.purpose = 0
      if self.blocking is None:
        self.blocking = False
      if self.message is None:
        self.message = ros_tum_msgs.msg.DialogueMessage()
      if self.replyType is None:
        self.replyType = 0
      if self.replyTo is None:
        self.replyTo = ''
      if self.defaultModalities is None:
        self.defaultModalities = []
      if self.preferredModalitiey is None:
        self.preferredModalitiey = []
    else:
      self.id = ''
      self.source = ''
      self.destination = ''
      self.category = 0
      self.purpose = 0
      self.blocking = False
      self.message = ros_tum_msgs.msg.DialogueMessage()
      self.replyType = 0
      self.replyTo = ''
      self.defaultModalities = []
      self.preferredModalitiey = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.destination
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2iB.pack(_x.category, _x.purpose, _x.blocking))
      _x = self.message.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i.pack(_x.message.messagePurpose, _x.replyType))
      _x = self.replyTo
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.defaultModalities)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.defaultModalities))
      length = len(self.preferredModalitiey)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.preferredModalitiey))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.message is None:
        self.message = ros_tum_msgs.msg.DialogueMessage()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8')
      else:
        self.id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source = str[start:end].decode('utf-8')
      else:
        self.source = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.destination = str[start:end].decode('utf-8')
      else:
        self.destination = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.category, _x.purpose, _x.blocking,) = _struct_2iB.unpack(str[start:end])
      self.blocking = bool(self.blocking)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message.message = str[start:end].decode('utf-8')
      else:
        self.message.message = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.message.messagePurpose, _x.replyType,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.replyTo = str[start:end].decode('utf-8')
      else:
        self.replyTo = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.defaultModalities = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.preferredModalitiey = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.destination
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2iB.pack(_x.category, _x.purpose, _x.blocking))
      _x = self.message.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i.pack(_x.message.messagePurpose, _x.replyType))
      _x = self.replyTo
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.defaultModalities)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.defaultModalities.tostring())
      length = len(self.preferredModalitiey)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.preferredModalitiey.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.message is None:
        self.message = ros_tum_msgs.msg.DialogueMessage()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8')
      else:
        self.id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source = str[start:end].decode('utf-8')
      else:
        self.source = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.destination = str[start:end].decode('utf-8')
      else:
        self.destination = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.category, _x.purpose, _x.blocking,) = _struct_2iB.unpack(str[start:end])
      self.blocking = bool(self.blocking)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message.message = str[start:end].decode('utf-8')
      else:
        self.message.message = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.message.messagePurpose, _x.replyType,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.replyTo = str[start:end].decode('utf-8')
      else:
        self.replyTo = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.defaultModalities = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.preferredModalitiey = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2iB = struct.Struct("<2iB")
_struct_2i = struct.Struct("<2i")
