/* DSblock model generated by Dymola from Modelica model Yeast
 Dymola Version 2013 FD01 (32-bit), 2012-10-18 translated this at Mon Jan 06 17:27:52 2014

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
DYMOLA_STATIC const char*modelName="Yeast";
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/diego/appdata/roaming/dynasim/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[4] = 310;
BoundParameterSection
InitialSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
X_[0] = DP_[2];
X_[1] = DP_[1];
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
W_[0] = DP_[4]*X_[1];
W_[2] = DP_[1]-X_[1];
W_[1] = DP_[5]*W_[2];
F_[0] = X_[0]*(W_[0]-W_[1]);
W_[3] = divmacro(310.0*X_[1]*X_[0]*DP_[3],"310.0*(s*p*C_f)",DP_[6],"T_ref");
 /* Linear system of equations to solve. */
F_[1] = RememberSimple_(F_[1], 0);
SolveScalarLinearParametric(DP_[0],"V",  -W_[3]," -f", F_[1],"der(s)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("V", "volume of fermentation vessel", 0, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("s0", "inital concentration of sugar", 1, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("p0", "initial population of yeast", 2, 1E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("C_f", "Feeding Coefficient [1/day] []", 3, 50, 0.0,0.0,0.0,0,560)
DeclareParameter("R", "Reproductivity [1/day] []", 4, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("S", "Sensitivity w.r.t. alcohol [1/day] []", 5, 15, 0.0,0.0,\
0.0,0,560)
DeclareParameter("T_ref", "reference temperature", 6, 300, 0.0,0.0,0.0,0,560)
DeclareState("p", "", 0, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(p)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("b", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("d", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("s", "concentration of sugar", 1, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(s)", "der(concentration of sugar)", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("a", "concentration of alcohol", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("f", "consumption of sugar (feeding)", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("T", "current temperature", 310, 0.0,0.0,0.0,0,513)
EndNonAlias(0)
#define NX_    2
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    5
#define NP_    7
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1402565836
#define NHash2_ 1575236377
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 1
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(F_[1], 0.0, 0);
EndEqBlock
EndDataBlock
