/* Auto-generated by genmsg_cpp for file /home/groupc/fuerte_workspace/sandbox/BILHR_ros/msg/LegPosition.msg */
#ifndef BILHR_ROS_MESSAGE_LEGPOSITION_H
#define BILHR_ROS_MESSAGE_LEGPOSITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace BILHR_ros
{
template <class ContainerAllocator>
struct LegPosition_ {
  typedef LegPosition_<ContainerAllocator> Type;

  LegPosition_()
  : LegPos(0)
  {
  }

  LegPosition_(const ContainerAllocator& _alloc)
  : LegPos(0)
  {
  }

  typedef uint8_t _LegPos_type;
  uint8_t LegPos;


  typedef boost::shared_ptr< ::BILHR_ros::LegPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BILHR_ros::LegPosition_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LegPosition
typedef  ::BILHR_ros::LegPosition_<std::allocator<void> > LegPosition;

typedef boost::shared_ptr< ::BILHR_ros::LegPosition> LegPositionPtr;
typedef boost::shared_ptr< ::BILHR_ros::LegPosition const> LegPositionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::BILHR_ros::LegPosition_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::BILHR_ros::LegPosition_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace BILHR_ros

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::BILHR_ros::LegPosition_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::BILHR_ros::LegPosition_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::BILHR_ros::LegPosition_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fd3820b3928d9e8f90df92433010335a";
  }

  static const char* value(const  ::BILHR_ros::LegPosition_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfd3820b3928d9e8fULL;
  static const uint64_t static_value2 = 0x90df92433010335aULL;
};

template<class ContainerAllocator>
struct DataType< ::BILHR_ros::LegPosition_<ContainerAllocator> > {
  static const char* value() 
  {
    return "BILHR_ros/LegPosition";
  }

  static const char* value(const  ::BILHR_ros::LegPosition_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::BILHR_ros::LegPosition_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 LegPos\n\
\n\
";
  }

  static const char* value(const  ::BILHR_ros::LegPosition_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::BILHR_ros::LegPosition_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::BILHR_ros::LegPosition_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.LegPos);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LegPosition_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BILHR_ros::LegPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::BILHR_ros::LegPosition_<ContainerAllocator> & v) 
  {
    s << indent << "LegPos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LegPos);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILHR_ROS_MESSAGE_LEGPOSITION_H

