#Dialogue ID in the form of UUID
string id

#Dialogue source
string source

#Dialogue destination
string destination

#Dialogue Category
int32 category

#Dialogue Purpose
int32 purpose

#Dialogue Blocking
bool blocking

#Dialogue Message
DialogueMessage message

#Dialogue Expected Reply Type
int32 replyType

#Dialogue ReplyTo UUID
string replyTo

#Dialogue default Modlaities
int32[] defaultModalities

#Dialogue Preferred Modalities
int32[] preferredModalitiey

