/* DSblock model generated by Dymola from Modelica model SimpleHydraulics.Examples.PressureWave
 Dymola Version 2013 FD01 (32-bit), 2012-10-18 translated this at Tue Nov 19 18:03:32 2013

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

BreakSectionFunctionDef(1)
BreakSectionFunctionDef(2)
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
DYMOLA_STATIC const char*modelName="SimpleHydraulics.Examples.PressureWave";
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/diego/appdata/roaming/dynasim/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC long QJacobianCG_[13]={3 , 4 , 1 , 2 , 5 , 7 , 3 , 3 , 6 , 9 , 2
   , 4 , 8};
DYMOLA_STATIC long QJacobianGC_[28]={
2 , 1 , 2 , 5 , 5 , 5 , 7 , 7 , 7 , 0 , 3 , 3 , 3 , 6 , 6 , 9 , 6 , 0 , 0 , 0 , 4
   , 0 , 4 , 8 , 8 , 8 , 0 , 0};
DYMOLA_STATIC double QJacobianCD_[10]={0  , 44 , 55 , 60 , 63 , 88 , 90 , 110 , 99
   , 120};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[25] = 3.141592653589793;
W_[22] = 0.0;
W_[21] = 0.0;
W_[20] = 0.0;
W_[24] = 0.0;
W_[18] = 0.0;
W_[19] = 0.0;
BoundParameterSection
InitialSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
 /* Linear system of equations to solve. */
F_[8] = RememberSimple_(F_[8], 0);
SolveScalarLinearParametric(DP_[27]*DP_[28],"pipeSection4.compressibleVolume.V*pipeSection4.compressibleVolume.kappa",
    -X_[6]," -pipeSection3.pipeMass.v", F_[8],"der(pipeSection4.compressibleVolume.hydPlug.p)");
 /* End of Equation Block */ 

W_[23] = DP_[29]*X_[6];
W_[17] = X_[8]-W_[23];
W_[14] = W_[17]-X_[7];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[0] = divmacro(1.0,"1.0",DP_[19],"pipeSection3.pipeMass.A");
F_[6] = RememberSimple_(F_[6], 1);
SolveScalarLinearParametric(helpvar[0]*DP_[18]*DP_[20],"pipeSection3.pipeMass.rho*pipeSection3.pipeMass.l/pipeSection3.pipeMass.A",
   W_[14],"pipeSection3.pipeMass.dp", F_[6],"der(pipeSection3.pipeMass.v)");
 /* End of Equation Block */ 

BreakSectionFunctionNew(1);
 /* Linear system of equations to solve. */
W_[13] = RememberSimple_(W_[13], 2);
SolveScalarLinearParametric((-1.0)*DP_[23]-DP_[17],"(-1.0)*pipeSection3.pipeFriction.k-pipeSection2.pipeFriction.k",
   X_[5]-X_[7],"pipeSection2.compressibleVolume.hydPlug.p-pipeSection3.compressibleVolume.hydPlug.p",
   W_[13],"pipeSection2.hydPlug_b.v");
W_[11] =  -DP_[17]*W_[13];
W_[16] = DP_[23]*W_[13];
 /* End of Equation Block */ 

BreakSectionFunctionNew(2);
W_[12] = X_[5]-W_[11];
W_[15] = X_[6]-W_[13];
 /* Linear system of equations to solve. */
F_[7] = RememberSimple_(F_[7], 3);
SolveScalarLinearParametric(DP_[21]*DP_[22],"pipeSection3.compressibleVolume.V*pipeSection3.compressibleVolume.kappa",
   W_[15],"pipeSection3.compressibleVolume.hydPlug.v", F_[7],"der(pipeSection3.compressibleVolume.hydPlug.p)");
 /* End of Equation Block */ 

W_[10] = W_[13]+X_[4];
 /* Linear system of equations to solve. */
F_[5] = RememberSimple_(F_[5], 4);
SolveScalarLinearParametric(DP_[15]*DP_[16],"pipeSection2.compressibleVolume.V*pipeSection2.compressibleVolume.kappa",
   W_[10],"pipeSection2.compressibleVolume.hydPlug.v", F_[5],"der(pipeSection2.compressibleVolume.hydPlug.p)");
 /* End of Equation Block */ 

W_[7] = DP_[11]*X_[4];
W_[8] = X_[3]-W_[7];
W_[9] = W_[8]-X_[5];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[1] = divmacro(1.0,"1.0",DP_[13],"pipeSection2.pipeMass.A");
F_[4] = RememberSimple_(F_[4], 5);
SolveScalarLinearParametric(helpvar[1]*DP_[12]*DP_[14],"pipeSection2.pipeMass.rho*pipeSection2.pipeMass.l/pipeSection2.pipeMass.A",
   W_[9],"pipeSection2.pipeMass.dp", F_[4],"der(pipeSection2.pipeMass.v)");
 /* End of Equation Block */ 

W_[6] = X_[2]-X_[4];
 /* Linear system of equations to solve. */
F_[3] = RememberSimple_(F_[3], 6);
SolveScalarLinearParametric(DP_[9]*DP_[10],"pipeSection1.compressibleVolume.V*pipeSection1.compressibleVolume.kappa",
   W_[6],"pipeSection1.compressibleVolume.hydPlug.v", F_[3],"der(pipeSection1.compressibleVolume.hydPlug.p)");
 /* End of Equation Block */ 

W_[3] = DP_[5]*X_[2];
W_[4] = X_[1]-W_[3];
W_[5] = W_[4]-X_[3];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[2] = divmacro(1.0,"1.0",DP_[7],"pipeSection1.pipeMass.A");
F_[2] = RememberSimple_(F_[2], 7);
SolveScalarLinearParametric(helpvar[2]*DP_[6]*DP_[8],"pipeSection1.pipeMass.rho*pipeSection1.pipeMass.l/pipeSection1.pipeMass.A",
   W_[5],"pipeSection1.pipeMass.dp", F_[2],"der(pipeSection1.pipeMass.v)");
 /* End of Equation Block */ 

W_[2] = X_[0]-X_[2];
 /* Linear system of equations to solve. */
F_[1] = RememberSimple_(F_[1], 8);
SolveScalarLinearParametric(DP_[3]*DP_[4],"pipeSection.compressibleVolume.V*pipeSection.compressibleVolume.kappa",
   W_[2],"pipeSection.compressibleVolume.hydPlug.v", F_[1],"der(pipeSection.compressibleVolume.hydPlug.p)");
 /* End of Equation Block */ 

W_[0] = DP_[33]+(IF LessTime(DP_[34], 0) THEN 0 ELSE DP_[30]*sin(
  6.283185307179586*DP_[31]*(Time-DP_[34])+DP_[32]));
W_[1] = W_[0]-X_[1];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[3] = divmacro(1.0,"1.0",DP_[1],"pipeSection.pipeMass.A");
F_[0] = RememberSimple_(F_[0], 9);
SolveScalarLinearParametric(helpvar[3]*DP_[0]*DP_[2],"pipeSection.pipeMass.rho*pipeSection.pipeMass.l/pipeSection.pipeMass.A",
   W_[1],"pipeSection.pipeMass.dp", F_[0],"der(pipeSection.pipeMass.v)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("signalPressure.hydPlug.p", "relative Pressure [Pa|bar]", 0.0, \
0.0,0.0,0.0,0,520)
DeclareAlias2("signalPressure.hydPlug.v", "volume flow [m3/s]", "pipeSection.pipeMass.v", -1,\
 1, 0, 132)
DeclareAlias2("signalPressure.u", "[Pa]", "signalPressure.hydPlug.p", 1, 5, 0, 0)
DeclareAlias2("pipeSection.pipeMass.hydPlug_a.p", "relative Pressure [Pa|bar]", \
"signalPressure.hydPlug.p", 1, 5, 0, 4)
DeclareAlias2("pipeSection.pipeMass.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection.pipeMass.v", 1, 1, 0, 132)
DeclareAlias2("pipeSection.pipeMass.hydPlug_b.p", "relative Pressure [Pa|bar]", \
"pipeSection.compressibleVolume.hydPlug.p", 1, 1, 1, 4)
DeclareAlias2("pipeSection.pipeMass.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection.pipeMass.v", -1, 1, 0, 132)
DeclareVariable("pipeSection.pipeMass.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("pipeSection.pipeMass.v", "[m3/s]", 0, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("pipeSection.pipeMass.der(v)", "[m3/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("pipeSection.pipeMass.rho", "[kg/m3|g/cm3]", 0, 1.29, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("pipeSection.pipeMass.A", "[m2]", 1, 0.01, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection.pipeMass.l", "[m]", 2, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection.compressibleVolume.V", "[m3]", 3, 0.002, 0.0,0.0,\
0.0,0,560)
DeclareParameter("pipeSection.compressibleVolume.kappa", "[1/Pa]", 4, 1E-005, \
0.0,0.0,0.0,0,560)
DeclareState("pipeSection.compressibleVolume.hydPlug.p", "relative Pressure [Pa|bar]",\
 1, 0.0, 0.0,0.0,0.0,0,568)
DeclareDerivative("pipeSection.compressibleVolume.hydPlug.der(p)", \
"der(relative Pressure) [Pa/s]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pipeSection.compressibleVolume.hydPlug.v", "volume flow [m3/s]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("pipeSection.pipeFriction.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection.compressibleVolume.hydPlug.p", 1, 1, 1, 4)
DeclareAlias2("pipeSection.pipeFriction.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection1.pipeMass.v", 1, 1, 2, 132)
DeclareAlias2("pipeSection.pipeFriction.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection.hydPlug_b.p", 1, 5, 4, 4)
DeclareAlias2("pipeSection.pipeFriction.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection1.pipeMass.v", -1, 1, 2, 132)
DeclareVariable("pipeSection.pipeFriction.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipeSection.pipeFriction.v", "[m3/s]", "pipeSection1.pipeMass.v", 1,\
 1, 2, 0)
DeclareParameter("pipeSection.pipeFriction.k", "[Pa.m-3.s]", 5, 5000, 0.0,0.0,\
0.0,0,560)
DeclareAlias2("pipeSection.hydPlug_a.p", "relative Pressure [Pa|bar]", \
"signalPressure.hydPlug.p", 1, 5, 0, 4)
DeclareAlias2("pipeSection.hydPlug_a.v", "volume flow [m3/s]", "pipeSection.pipeMass.v", 1,\
 1, 0, 132)
DeclareVariable("pipeSection.hydPlug_b.p", "relative Pressure [Pa|bar]", 0.0, \
0.0,0.0,0.0,0,520)
DeclareAlias2("pipeSection.hydPlug_b.v", "volume flow [m3/s]", "pipeSection1.pipeMass.v", -1,\
 1, 2, 132)
DeclareAlias2("pipeSection1.pipeMass.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection.hydPlug_b.p", 1, 5, 4, 4)
DeclareAlias2("pipeSection1.pipeMass.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection1.pipeMass.v", 1, 1, 2, 132)
DeclareAlias2("pipeSection1.pipeMass.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection1.compressibleVolume.hydPlug.p", 1, 1, 3, 4)
DeclareAlias2("pipeSection1.pipeMass.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection1.pipeMass.v", -1, 1, 2, 132)
DeclareVariable("pipeSection1.pipeMass.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("pipeSection1.pipeMass.v", "[m3/s]", 2, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("pipeSection1.pipeMass.der(v)", "[m3/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("pipeSection1.pipeMass.rho", "[kg/m3|g/cm3]", 6, 1.29, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("pipeSection1.pipeMass.A", "[m2]", 7, 0.01, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection1.pipeMass.l", "[m]", 8, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection1.compressibleVolume.V", "[m3]", 9, 0.002, 0.0,0.0,\
0.0,0,560)
DeclareParameter("pipeSection1.compressibleVolume.kappa", "[1/Pa]", 10, 1E-005, \
0.0,0.0,0.0,0,560)
DeclareState("pipeSection1.compressibleVolume.hydPlug.p", "relative Pressure [Pa|bar]",\
 3, 0.0, 0.0,0.0,0.0,0,568)
DeclareDerivative("pipeSection1.compressibleVolume.hydPlug.der(p)", \
"der(relative Pressure) [Pa/s]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pipeSection1.compressibleVolume.hydPlug.v", "volume flow [m3/s]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("pipeSection1.pipeFriction.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection1.compressibleVolume.hydPlug.p", 1, 1, 3, 4)
DeclareAlias2("pipeSection1.pipeFriction.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection2.pipeMass.v", 1, 1, 4, 132)
DeclareAlias2("pipeSection1.pipeFriction.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection1.hydPlug_b.p", 1, 5, 8, 4)
DeclareAlias2("pipeSection1.pipeFriction.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection2.pipeMass.v", -1, 1, 4, 132)
DeclareVariable("pipeSection1.pipeFriction.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipeSection1.pipeFriction.v", "[m3/s]", "pipeSection2.pipeMass.v", 1,\
 1, 4, 0)
DeclareParameter("pipeSection1.pipeFriction.k", "[Pa.m-3.s]", 11, 5000, 0.0,0.0,\
0.0,0,560)
DeclareAlias2("pipeSection1.hydPlug_a.p", "relative Pressure [Pa|bar]", \
"pipeSection.hydPlug_b.p", 1, 5, 4, 4)
DeclareAlias2("pipeSection1.hydPlug_a.v", "volume flow [m3/s]", "pipeSection1.pipeMass.v", 1,\
 1, 2, 132)
DeclareVariable("pipeSection1.hydPlug_b.p", "relative Pressure [Pa|bar]", 0.0, \
0.0,0.0,0.0,0,520)
DeclareAlias2("pipeSection1.hydPlug_b.v", "volume flow [m3/s]", "pipeSection2.pipeMass.v", -1,\
 1, 4, 132)
DeclareAlias2("pipeSection2.pipeMass.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection1.hydPlug_b.p", 1, 5, 8, 4)
DeclareAlias2("pipeSection2.pipeMass.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection2.pipeMass.v", 1, 1, 4, 132)
DeclareAlias2("pipeSection2.pipeMass.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection2.compressibleVolume.hydPlug.p", 1, 1, 5, 4)
DeclareAlias2("pipeSection2.pipeMass.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection2.pipeMass.v", -1, 1, 4, 132)
DeclareVariable("pipeSection2.pipeMass.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("pipeSection2.pipeMass.v", "[m3/s]", 4, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("pipeSection2.pipeMass.der(v)", "[m3/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("pipeSection2.pipeMass.rho", "[kg/m3|g/cm3]", 12, 1.29, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("pipeSection2.pipeMass.A", "[m2]", 13, 0.01, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection2.pipeMass.l", "[m]", 14, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection2.compressibleVolume.V", "[m3]", 15, 0.002, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection2.compressibleVolume.kappa", "[1/Pa]", 16, 1E-005, \
0.0,0.0,0.0,0,560)
DeclareState("pipeSection2.compressibleVolume.hydPlug.p", "relative Pressure [Pa|bar]",\
 5, 0.0, 0.0,0.0,0.0,0,568)
DeclareDerivative("pipeSection2.compressibleVolume.hydPlug.der(p)", \
"der(relative Pressure) [Pa/s]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pipeSection2.compressibleVolume.hydPlug.v", "volume flow [m3/s]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("pipeSection2.pipeFriction.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection2.compressibleVolume.hydPlug.p", 1, 1, 5, 4)
DeclareAlias2("pipeSection2.pipeFriction.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection2.hydPlug_b.v", -1, 5, 13, 132)
DeclareAlias2("pipeSection2.pipeFriction.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection2.hydPlug_b.p", 1, 5, 12, 4)
DeclareAlias2("pipeSection2.pipeFriction.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection2.hydPlug_b.v", 1, 5, 13, 132)
DeclareVariable("pipeSection2.pipeFriction.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipeSection2.pipeFriction.v", "[m3/s]", "pipeSection2.hydPlug_b.v", -1,\
 5, 13, 0)
DeclareParameter("pipeSection2.pipeFriction.k", "[Pa.m-3.s]", 17, 5000, 0.0,0.0,\
0.0,0,560)
DeclareAlias2("pipeSection2.hydPlug_a.p", "relative Pressure [Pa|bar]", \
"pipeSection1.hydPlug_b.p", 1, 5, 8, 4)
DeclareAlias2("pipeSection2.hydPlug_a.v", "volume flow [m3/s]", "pipeSection2.pipeMass.v", 1,\
 1, 4, 132)
DeclareVariable("pipeSection2.hydPlug_b.p", "relative Pressure [Pa|bar]", 0.0, \
0.0,0.0,0.0,0,520)
DeclareVariable("pipeSection2.hydPlug_b.v", "volume flow [m3/s]", 0.0, 0.0,0.0,\
0.0,0,776)
DeclareAlias2("pipeSection3.pipeMass.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection3.hydPlug_a.p", 1, 5, 17, 4)
DeclareAlias2("pipeSection3.pipeMass.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection3.pipeMass.v", 1, 1, 6, 132)
DeclareAlias2("pipeSection3.pipeMass.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection3.compressibleVolume.hydPlug.p", 1, 1, 7, 4)
DeclareAlias2("pipeSection3.pipeMass.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection3.pipeMass.v", -1, 1, 6, 132)
DeclareVariable("pipeSection3.pipeMass.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("pipeSection3.pipeMass.v", "[m3/s]", 6, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("pipeSection3.pipeMass.der(v)", "[m3/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("pipeSection3.pipeMass.rho", "[kg/m3|g/cm3]", 18, 1.29, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("pipeSection3.pipeMass.A", "[m2]", 19, 0.01, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection3.pipeMass.l", "[m]", 20, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection3.compressibleVolume.V", "[m3]", 21, 0.002, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection3.compressibleVolume.kappa", "[1/Pa]", 22, 1E-005, \
0.0,0.0,0.0,0,560)
DeclareState("pipeSection3.compressibleVolume.hydPlug.p", "relative Pressure [Pa|bar]",\
 7, 0.0, 0.0,0.0,0.0,0,568)
DeclareDerivative("pipeSection3.compressibleVolume.hydPlug.der(p)", \
"der(relative Pressure) [Pa/s]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pipeSection3.compressibleVolume.hydPlug.v", "volume flow [m3/s]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("pipeSection3.pipeFriction.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection3.compressibleVolume.hydPlug.p", 1, 1, 7, 4)
DeclareAlias2("pipeSection3.pipeFriction.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection2.hydPlug_b.v", 1, 5, 13, 132)
DeclareAlias2("pipeSection3.pipeFriction.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection2.hydPlug_b.p", 1, 5, 12, 4)
DeclareAlias2("pipeSection3.pipeFriction.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection2.hydPlug_b.v", -1, 5, 13, 132)
DeclareVariable("pipeSection3.pipeFriction.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipeSection3.pipeFriction.v", "[m3/s]", "pipeSection2.hydPlug_b.v", 1,\
 5, 13, 0)
DeclareParameter("pipeSection3.pipeFriction.k", "[Pa.m-3.s]", 23, 5000, 0.0,0.0,\
0.0,0,560)
DeclareVariable("pipeSection3.hydPlug_a.p", "relative Pressure [Pa|bar]", 0.0, \
0.0,0.0,0.0,0,520)
DeclareAlias2("pipeSection3.hydPlug_a.v", "volume flow [m3/s]", "pipeSection3.pipeMass.v", 1,\
 1, 6, 132)
DeclareAlias2("pipeSection3.hydPlug_b.p", "relative Pressure [Pa|bar]", \
"pipeSection2.hydPlug_b.p", 1, 5, 12, 4)
DeclareAlias2("pipeSection3.hydPlug_b.v", "volume flow [m3/s]", "pipeSection2.hydPlug_b.v", -1,\
 5, 13, 132)
DeclareAlias2("pipeSection4.pipeMass.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection4.compressibleVolume.hydPlug.p", 1, 1, 8, 4)
DeclareVariable("pipeSection4.pipeMass.hydPlug_a.v", "volume flow [m3/s]", 0.0, \
0.0,0.0,0.0,0,777)
DeclareAlias2("pipeSection4.pipeMass.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection4.compressibleVolume.hydPlug.p", 1, 1, 8, 4)
DeclareVariable("pipeSection4.pipeMass.hydPlug_b.v", "volume flow [m3/s]", 0.0, \
0.0,0.0,0.0,0,777)
DeclareVariable("pipeSection4.pipeMass.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipeSection4.pipeMass.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipeSection4.pipeMass.der(v)", "[m3/s2]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("pipeSection4.pipeMass.rho", "[kg/m3|g/cm3]", 24, 1.29, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("pipeSection4.pipeMass.A", "[m2]", 25, 0.01, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection4.pipeMass.l", "[m]", 26, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection4.compressibleVolume.V", "[m3]", 27, 0.002, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipeSection4.compressibleVolume.kappa", "[1/Pa]", 28, 1E-005, \
0.0,0.0,0.0,0,560)
DeclareState("pipeSection4.compressibleVolume.hydPlug.p", "relative Pressure [Pa|bar]",\
 8, 0.0, 0.0,0.0,0.0,0,568)
DeclareDerivative("pipeSection4.compressibleVolume.hydPlug.der(p)", \
"der(relative Pressure) [Pa/s]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("pipeSection4.compressibleVolume.hydPlug.v", "volume flow [m3/s]",\
 "pipeSection3.pipeMass.v", -1, 1, 6, 132)
DeclareAlias2("pipeSection4.pipeFriction.hydPlug_a.p", "relative Pressure [Pa|bar]",\
 "pipeSection4.compressibleVolume.hydPlug.p", 1, 1, 8, 4)
DeclareAlias2("pipeSection4.pipeFriction.hydPlug_a.v", "volume flow [m3/s]", \
"pipeSection3.pipeMass.v", 1, 1, 6, 132)
DeclareAlias2("pipeSection4.pipeFriction.hydPlug_b.p", "relative Pressure [Pa|bar]",\
 "pipeSection3.hydPlug_a.p", 1, 5, 17, 4)
DeclareAlias2("pipeSection4.pipeFriction.hydPlug_b.v", "volume flow [m3/s]", \
"pipeSection3.pipeMass.v", -1, 1, 6, 132)
DeclareVariable("pipeSection4.pipeFriction.dp", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipeSection4.pipeFriction.v", "[m3/s]", "pipeSection3.pipeMass.v", 1,\
 1, 6, 0)
DeclareParameter("pipeSection4.pipeFriction.k", "[Pa.m-3.s]", 29, 5000, 0.0,0.0,\
0.0,0,560)
DeclareAlias2("pipeSection4.hydPlug_a.p", "relative Pressure [Pa|bar]", \
"pipeSection4.compressibleVolume.hydPlug.p", 1, 1, 8, 4)
DeclareVariable("pipeSection4.hydPlug_a.v", "volume flow [m3/s]", 0.0, 0.0,0.0,\
0.0,0,777)
DeclareAlias2("pipeSection4.hydPlug_b.p", "relative Pressure [Pa|bar]", \
"pipeSection3.hydPlug_a.p", 1, 5, 17, 4)
DeclareAlias2("pipeSection4.hydPlug_b.v", "volume flow [m3/s]", "pipeSection3.pipeMass.v", -1,\
 1, 6, 132)
DeclareParameter("sine.amplitude", "Amplitude of sine wave", 30, 10000.0, \
0.0,0.0,0.0,0,560)
DeclareParameter("sine.freqHz", "Frequency of sine wave [Hz]", 31, 60, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sine.phase", "Phase of sine wave [rad|deg]", 32, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sine.offset", "Offset of output signal", 33, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("sine.startTime", "Output = offset for time < startTime [s]", 34,\
 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("sine.y", "Connector of Real output signal [Pa]", "signalPressure.hydPlug.p", 1,\
 5, 0, 0)
DeclareVariable("sine.pi", "", 3.141592653589793, 0.0,0.0,0.0,0,2561)
EndNonAlias(0)
#define NX_    9
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    26
#define NP_    35
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 182882305
#define NHash2_ -1420695549
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    61
#define SizePre_ 0
#define SizeEq_ 10
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 4
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(F_[1], 0.0, 8);
DoRemember_(F_[0], 0.0, 9);
DoRemember_(F_[3], 0.0, 6);
DoRemember_(F_[2], 0.0, 7);
DoRemember_(F_[5], 0.0, 4);
DoRemember_(F_[4], 0.0, 5);
DoRemember_(F_[7], 0.0, 3);
DoRemember_(F_[6], 0.0, 1);
DoRemember_(F_[8], 0.0, 0);
DoRemember_(W_[13], 0.0, 2);
EndEqBlock
EndDataBlock
