/* DSblock model generated by Dymola from Modelica model myHydraulics.Examples.Example1
 Dymola Version 2013 FD01 (32-bit), 2012-10-18 translated this at Tue Nov 19 18:06:35 2013

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
DYMOLA_STATIC const char*modelName="myHydraulics.Examples.Example1";
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/diego/appdata/roaming/dynasim/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC long QJacobianCG_[15]={4 , 4 , 1 , 2 , 5 , 9 , 2 , 3 , 7 , 2 , 4
   , 8 , 2 , 6 , 10};
DYMOLA_STATIC long QJacobianGC_[41]={
2 , 1 , 0 , 1 , 0 , 5 , 0 , 5 , 0 , 9 , 0 , 0 , 0 , 3 , 0 , 3 , 0 , 7 , 0 , 7 , 4
   , 0 , 4 , 4 , 8 , 0 , 8 , 8 , 0 , 0 , 0 , 0 , 6 , 0 , 6 , 6 , 10 , 0 , 10 , 10
   , 0};
DYMOLA_STATIC double QJacobianCD_[11]={0  , 44 , 55 , 60 , 63 , 88 , 72 , 100 , 99
   , 132 , 104};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[28] = 3.141592653589793;
W_[22] = 0.0;
W_[3] = 0.0;
W_[9] = 0.0;
W_[14] = 0.0;
W_[19] = 0.0;
W_[26] = 0.0;
W_[27] = 0.0;
W_[24] = 0.0;
W_[25] = 0.0;
W_[23] = 0.0;
BoundParameterSection
InitialSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
 /* Linear system of equations to solve. */
F_[8] = RememberSimple_(F_[8], 0);
SolveScalarLinearParametric(DP_[28]*DP_[30]*DP_[29],"section4.compresiveVolume.Kc*section4.compresiveVolume.A*section4.compresiveVolume.L",
   X_[9],"section4.hydraulicInductance.v", F_[8],"der(section4.compresiveVolume.P)");
 /* End of Equation Block */ 

W_[18] = DP_[27]*X_[9];
W_[20] = X_[6]-W_[18];
W_[21] = W_[20]-X_[8];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[0] = divmacro(1.0,"1.0",DP_[33],"section4.hydraulicInductance.A");
F_[9] = RememberSimple_(F_[9], 1);
SolveScalarLinearParametric(helpvar[0]*DP_[32]*DP_[31],"section4.hydraulicInductance.D*section4.hydraulicInductance.L/section4.hydraulicInductance.A",
   W_[21],"section4.hydraulicInductance.P", F_[9],"der(section4.hydraulicInductance.v)");
 /* End of Equation Block */ 

W_[16] = X_[7]-X_[9];
 /* Linear system of equations to solve. */
F_[6] = RememberSimple_(F_[6], 2);
SolveScalarLinearParametric(DP_[21]*DP_[23]*DP_[22],"section3.compresiveVolume.Kc*section3.compresiveVolume.A*section3.compresiveVolume.L",
   W_[16],"section3.compresiveVolume.v", F_[6],"der(section3.compresiveVolume.P)");
 /* End of Equation Block */ 

W_[13] = DP_[20]*X_[7];
W_[15] = X_[4]-W_[13];
W_[17] = W_[15]-X_[6];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[1] = divmacro(1.0,"1.0",DP_[26],"section3.hydraulicInductance.A");
F_[7] = RememberSimple_(F_[7], 3);
SolveScalarLinearParametric(helpvar[1]*DP_[25]*DP_[24],"section3.hydraulicInductance.D*section3.hydraulicInductance.L/section3.hydraulicInductance.A",
   W_[17],"section3.hydraulicInductance.P", F_[7],"der(section3.hydraulicInductance.v)");
 /* End of Equation Block */ 

W_[11] = X_[5]-X_[7];
 /* Linear system of equations to solve. */
F_[4] = RememberSimple_(F_[4], 4);
SolveScalarLinearParametric(DP_[14]*DP_[16]*DP_[15],"section2.compresiveVolume.Kc*section2.compresiveVolume.A*section2.compresiveVolume.L",
   W_[11],"section2.compresiveVolume.v", F_[4],"der(section2.compresiveVolume.P)");
 /* End of Equation Block */ 

W_[8] = DP_[13]*X_[5];
W_[10] = X_[2]-W_[8];
W_[12] = W_[10]-X_[4];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[2] = divmacro(1.0,"1.0",DP_[19],"section2.hydraulicInductance.A");
F_[5] = RememberSimple_(F_[5], 5);
SolveScalarLinearParametric(helpvar[2]*DP_[18]*DP_[17],"section2.hydraulicInductance.D*section2.hydraulicInductance.L/section2.hydraulicInductance.A",
   W_[12],"section2.hydraulicInductance.P", F_[5],"der(section2.hydraulicInductance.v)");
 /* End of Equation Block */ 

W_[6] = X_[3]-X_[5];
 /* Linear system of equations to solve. */
F_[2] = RememberSimple_(F_[2], 6);
SolveScalarLinearParametric(DP_[7]*DP_[9]*DP_[8],"section1.compresiveVolume.Kc*section1.compresiveVolume.A*section1.compresiveVolume.L",
   W_[6],"section1.compresiveVolume.v", F_[2],"der(section1.compresiveVolume.P)");
 /* End of Equation Block */ 

W_[2] = DP_[6]*X_[3];
W_[5] = X_[0]-W_[2];
W_[7] = W_[5]-X_[2];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[3] = divmacro(1.0,"1.0",DP_[12],"section1.hydraulicInductance.A");
F_[3] = RememberSimple_(F_[3], 7);
SolveScalarLinearParametric(helpvar[3]*DP_[11]*DP_[10],"section1.hydraulicInductance.D*section1.hydraulicInductance.L/section1.hydraulicInductance.A",
   W_[7],"section1.hydraulicInductance.P", F_[3],"der(section1.hydraulicInductance.v)");
 /* End of Equation Block */ 

W_[0] = X_[1]-X_[3];
 /* Linear system of equations to solve. */
F_[0] = RememberSimple_(F_[0], 8);
SolveScalarLinearParametric(DP_[0]*DP_[2]*DP_[1],"section.compresiveVolume.Kc*section.compresiveVolume.A*section.compresiveVolume.L",
   W_[0],"section.compresiveVolume.v", F_[0],"der(section.compresiveVolume.P)");
 /* End of Equation Block */ 

W_[4] = DP_[38]+(IF LessTime(DP_[39], 0) THEN 0 ELSE DP_[35]*sin(
  6.283185307179586*DP_[36]*(Time-DP_[39])+DP_[37]));
W_[1] = W_[4]-X_[0];
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
helpvar[4] = divmacro(1.0,"1.0",DP_[5],"section.hydraulicInductance.A");
F_[1] = RememberSimple_(F_[1], 9);
SolveScalarLinearParametric(helpvar[4]*DP_[4]*DP_[3],"section.hydraulicInductance.D*section.hydraulicInductance.L/section.hydraulicInductance.A",
   W_[1],"section.hydraulicInductance.P", F_[1],"der(section.hydraulicInductance.v)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareState("section.compresiveVolume.P", "[Pa|bar]", 0, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section.compresiveVolume.der(P)", "[Pa/s]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("section.compresiveVolume.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("section.compresiveVolume.Kc", "", 0, 1E-005, 0.0,0.0,0.0,0,560)
DeclareParameter("section.compresiveVolume.L", "", 1, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section.compresiveVolume.A", "", 2, 0.01, 0.0,0.0,0.0,0,560)
DeclareAlias2("section.compresiveVolume.first.P", "[Pa|bar]", "section.compresiveVolume.P", 1,\
 1, 0, 4)
DeclareAlias2("section.compresiveVolume.first.v", "[m3/s]", "section.compresiveVolume.v", 1,\
 5, 0, 132)
DeclareVariable("section.hydraulicInductance.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("section.hydraulicInductance.v", "[m3/s]", 1, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section.hydraulicInductance.der(v)", "[m3/s2]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("section.hydraulicInductance.first.P", "[Pa|bar]", "section.pin.P", 1,\
 5, 4, 4)
DeclareAlias2("section.hydraulicInductance.first.v", "[m3/s]", "section.hydraulicInductance.v", 1,\
 1, 1, 132)
DeclareAlias2("section.hydraulicInductance.second.P", "[Pa|bar]", \
"section.compresiveVolume.P", 1, 1, 0, 4)
DeclareAlias2("section.hydraulicInductance.second.v", "[m3/s]", "section.hydraulicInductance.v", -1,\
 1, 1, 132)
DeclareParameter("section.hydraulicInductance.L", "", 3, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section.hydraulicInductance.D", "", 4, 1.29, 0.0,0.0,0.0,0,560)
DeclareParameter("section.hydraulicInductance.A", "", 5, 0.01, 0.0,0.0,0.0,0,560)
DeclareVariable("section.pipeFriction.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("section.pipeFriction.v", "[m3/s]", "section1.hydraulicInductance.v", 1,\
 1, 3, 0)
DeclareAlias2("section.pipeFriction.first.P", "[Pa|bar]", "section.compresiveVolume.P", 1,\
 1, 0, 4)
DeclareAlias2("section.pipeFriction.first.v", "[m3/s]", "section1.hydraulicInductance.v", 1,\
 1, 3, 132)
DeclareAlias2("section.pipeFriction.second.P", "[Pa|bar]", "section.pin2.P", 1, 5,\
 5, 4)
DeclareAlias2("section.pipeFriction.second.v", "[m3/s]", "section1.hydraulicInductance.v", -1,\
 1, 3, 132)
DeclareParameter("section.pipeFriction.Kr", "[Pa.m-3.s]", 6, 5000, 0.0,0.0,0.0,0,560)
DeclareAlias2("section.pin1.P", "[Pa|bar]", "section.compresiveVolume.P", 1, 1, 0,\
 1028)
DeclareVariable("section.pin1.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,2825)
DeclareVariable("section.pin.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("section.pin.v", "[m3/s]", "section.hydraulicInductance.v", 1, 1, 1,\
 132)
DeclareVariable("section.pin2.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("section.pin2.v", "[m3/s]", "section1.hydraulicInductance.v", -1, 1,\
 3, 132)
DeclareState("section1.compresiveVolume.P", "[Pa|bar]", 2, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section1.compresiveVolume.der(P)", "[Pa/s]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("section1.compresiveVolume.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("section1.compresiveVolume.Kc", "", 7, 1E-005, 0.0,0.0,0.0,0,560)
DeclareParameter("section1.compresiveVolume.L", "", 8, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section1.compresiveVolume.A", "", 9, 0.01, 0.0,0.0,0.0,0,560)
DeclareAlias2("section1.compresiveVolume.first.P", "[Pa|bar]", "section1.compresiveVolume.P", 1,\
 1, 2, 4)
DeclareAlias2("section1.compresiveVolume.first.v", "[m3/s]", "section1.compresiveVolume.v", 1,\
 5, 6, 132)
DeclareVariable("section1.hydraulicInductance.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("section1.hydraulicInductance.v", "[m3/s]", 3, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section1.hydraulicInductance.der(v)", "[m3/s2]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("section1.hydraulicInductance.first.P", "[Pa|bar]", \
"section.pin2.P", 1, 5, 5, 4)
DeclareAlias2("section1.hydraulicInductance.first.v", "[m3/s]", "section1.hydraulicInductance.v", 1,\
 1, 3, 132)
DeclareAlias2("section1.hydraulicInductance.second.P", "[Pa|bar]", \
"section1.compresiveVolume.P", 1, 1, 2, 4)
DeclareAlias2("section1.hydraulicInductance.second.v", "[m3/s]", \
"section1.hydraulicInductance.v", -1, 1, 3, 132)
DeclareParameter("section1.hydraulicInductance.L", "", 10, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section1.hydraulicInductance.D", "", 11, 1.29, 0.0,0.0,0.0,0,560)
DeclareParameter("section1.hydraulicInductance.A", "", 12, 0.01, 0.0,0.0,0.0,0,560)
DeclareVariable("section1.pipeFriction.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("section1.pipeFriction.v", "[m3/s]", "section2.hydraulicInductance.v", 1,\
 1, 5, 0)
DeclareAlias2("section1.pipeFriction.first.P", "[Pa|bar]", "section1.compresiveVolume.P", 1,\
 1, 2, 4)
DeclareAlias2("section1.pipeFriction.first.v", "[m3/s]", "section2.hydraulicInductance.v", 1,\
 1, 5, 132)
DeclareAlias2("section1.pipeFriction.second.P", "[Pa|bar]", "section1.pin2.P", 1,\
 5, 10, 4)
DeclareAlias2("section1.pipeFriction.second.v", "[m3/s]", "section2.hydraulicInductance.v", -1,\
 1, 5, 132)
DeclareParameter("section1.pipeFriction.Kr", "[Pa.m-3.s]", 13, 5000, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("section1.pin1.P", "[Pa|bar]", "section1.compresiveVolume.P", 1, 1,\
 2, 1028)
DeclareVariable("section1.pin1.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,2825)
DeclareAlias2("section1.pin.P", "[Pa|bar]", "section.pin2.P", 1, 5, 5, 4)
DeclareAlias2("section1.pin.v", "[m3/s]", "section1.hydraulicInductance.v", 1, 1,\
 3, 132)
DeclareVariable("section1.pin2.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("section1.pin2.v", "[m3/s]", "section2.hydraulicInductance.v", -1,\
 1, 5, 132)
DeclareState("section2.compresiveVolume.P", "[Pa|bar]", 4, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section2.compresiveVolume.der(P)", "[Pa/s]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("section2.compresiveVolume.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("section2.compresiveVolume.Kc", "", 14, 1E-005, 0.0,0.0,0.0,0,560)
DeclareParameter("section2.compresiveVolume.L", "", 15, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section2.compresiveVolume.A", "", 16, 0.01, 0.0,0.0,0.0,0,560)
DeclareAlias2("section2.compresiveVolume.first.P", "[Pa|bar]", "section2.compresiveVolume.P", 1,\
 1, 4, 4)
DeclareAlias2("section2.compresiveVolume.first.v", "[m3/s]", "section2.compresiveVolume.v", 1,\
 5, 11, 132)
DeclareVariable("section2.hydraulicInductance.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("section2.hydraulicInductance.v", "[m3/s]", 5, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section2.hydraulicInductance.der(v)", "[m3/s2]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("section2.hydraulicInductance.first.P", "[Pa|bar]", \
"section1.pin2.P", 1, 5, 10, 4)
DeclareAlias2("section2.hydraulicInductance.first.v", "[m3/s]", "section2.hydraulicInductance.v", 1,\
 1, 5, 132)
DeclareAlias2("section2.hydraulicInductance.second.P", "[Pa|bar]", \
"section2.compresiveVolume.P", 1, 1, 4, 4)
DeclareAlias2("section2.hydraulicInductance.second.v", "[m3/s]", \
"section2.hydraulicInductance.v", -1, 1, 5, 132)
DeclareParameter("section2.hydraulicInductance.L", "", 17, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section2.hydraulicInductance.D", "", 18, 1.29, 0.0,0.0,0.0,0,560)
DeclareParameter("section2.hydraulicInductance.A", "", 19, 0.01, 0.0,0.0,0.0,0,560)
DeclareVariable("section2.pipeFriction.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("section2.pipeFriction.v", "[m3/s]", "section3.hydraulicInductance.v", 1,\
 1, 7, 0)
DeclareAlias2("section2.pipeFriction.first.P", "[Pa|bar]", "section2.compresiveVolume.P", 1,\
 1, 4, 4)
DeclareAlias2("section2.pipeFriction.first.v", "[m3/s]", "section3.hydraulicInductance.v", 1,\
 1, 7, 132)
DeclareAlias2("section2.pipeFriction.second.P", "[Pa|bar]", "section2.pin2.P", 1,\
 5, 15, 4)
DeclareAlias2("section2.pipeFriction.second.v", "[m3/s]", "section3.hydraulicInductance.v", -1,\
 1, 7, 132)
DeclareParameter("section2.pipeFriction.Kr", "[Pa.m-3.s]", 20, 5000, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("section2.pin1.P", "[Pa|bar]", "section2.compresiveVolume.P", 1, 1,\
 4, 1028)
DeclareVariable("section2.pin1.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,2825)
DeclareAlias2("section2.pin.P", "[Pa|bar]", "section1.pin2.P", 1, 5, 10, 4)
DeclareAlias2("section2.pin.v", "[m3/s]", "section2.hydraulicInductance.v", 1, 1,\
 5, 132)
DeclareVariable("section2.pin2.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("section2.pin2.v", "[m3/s]", "section3.hydraulicInductance.v", -1,\
 1, 7, 132)
DeclareState("section3.compresiveVolume.P", "[Pa|bar]", 6, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section3.compresiveVolume.der(P)", "[Pa/s]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("section3.compresiveVolume.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("section3.compresiveVolume.Kc", "", 21, 1E-005, 0.0,0.0,0.0,0,560)
DeclareParameter("section3.compresiveVolume.L", "", 22, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section3.compresiveVolume.A", "", 23, 0.01, 0.0,0.0,0.0,0,560)
DeclareAlias2("section3.compresiveVolume.first.P", "[Pa|bar]", "section3.compresiveVolume.P", 1,\
 1, 6, 4)
DeclareAlias2("section3.compresiveVolume.first.v", "[m3/s]", "section3.compresiveVolume.v", 1,\
 5, 16, 132)
DeclareVariable("section3.hydraulicInductance.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("section3.hydraulicInductance.v", "[m3/s]", 7, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section3.hydraulicInductance.der(v)", "[m3/s2]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("section3.hydraulicInductance.first.P", "[Pa|bar]", \
"section2.pin2.P", 1, 5, 15, 4)
DeclareAlias2("section3.hydraulicInductance.first.v", "[m3/s]", "section3.hydraulicInductance.v", 1,\
 1, 7, 132)
DeclareAlias2("section3.hydraulicInductance.second.P", "[Pa|bar]", \
"section3.compresiveVolume.P", 1, 1, 6, 4)
DeclareAlias2("section3.hydraulicInductance.second.v", "[m3/s]", \
"section3.hydraulicInductance.v", -1, 1, 7, 132)
DeclareParameter("section3.hydraulicInductance.L", "", 24, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section3.hydraulicInductance.D", "", 25, 1.29, 0.0,0.0,0.0,0,560)
DeclareParameter("section3.hydraulicInductance.A", "", 26, 0.01, 0.0,0.0,0.0,0,560)
DeclareVariable("section3.pipeFriction.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("section3.pipeFriction.v", "[m3/s]", "section4.hydraulicInductance.v", 1,\
 1, 9, 0)
DeclareAlias2("section3.pipeFriction.first.P", "[Pa|bar]", "section3.compresiveVolume.P", 1,\
 1, 6, 4)
DeclareAlias2("section3.pipeFriction.first.v", "[m3/s]", "section4.hydraulicInductance.v", 1,\
 1, 9, 132)
DeclareAlias2("section3.pipeFriction.second.P", "[Pa|bar]", "section3.pin2.P", 1,\
 5, 20, 4)
DeclareAlias2("section3.pipeFriction.second.v", "[m3/s]", "section4.hydraulicInductance.v", -1,\
 1, 9, 132)
DeclareParameter("section3.pipeFriction.Kr", "[Pa.m-3.s]", 27, 5000, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("section3.pin1.P", "[Pa|bar]", "section3.compresiveVolume.P", 1, 1,\
 6, 1028)
DeclareVariable("section3.pin1.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,2825)
DeclareAlias2("section3.pin.P", "[Pa|bar]", "section2.pin2.P", 1, 5, 15, 4)
DeclareAlias2("section3.pin.v", "[m3/s]", "section3.hydraulicInductance.v", 1, 1,\
 7, 132)
DeclareVariable("section3.pin2.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("section3.pin2.v", "[m3/s]", "section4.hydraulicInductance.v", -1,\
 1, 9, 132)
DeclareState("section4.compresiveVolume.P", "[Pa|bar]", 8, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section4.compresiveVolume.der(P)", "[Pa/s]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareAlias2("section4.compresiveVolume.v", "[m3/s]", "section4.hydraulicInductance.v", 1,\
 1, 9, 0)
DeclareParameter("section4.compresiveVolume.Kc", "", 28, 1E-005, 0.0,0.0,0.0,0,560)
DeclareParameter("section4.compresiveVolume.L", "", 29, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section4.compresiveVolume.A", "", 30, 0.01, 0.0,0.0,0.0,0,560)
DeclareAlias2("section4.compresiveVolume.first.P", "[Pa|bar]", "section4.compresiveVolume.P", 1,\
 1, 8, 4)
DeclareAlias2("section4.compresiveVolume.first.v", "[m3/s]", "section4.hydraulicInductance.v", 1,\
 1, 9, 132)
DeclareVariable("section4.hydraulicInductance.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("section4.hydraulicInductance.v", "[m3/s]", 9, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("section4.hydraulicInductance.der(v)", "[m3/s2]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("section4.hydraulicInductance.first.P", "[Pa|bar]", \
"section3.pin2.P", 1, 5, 20, 4)
DeclareAlias2("section4.hydraulicInductance.first.v", "[m3/s]", "section4.hydraulicInductance.v", 1,\
 1, 9, 132)
DeclareAlias2("section4.hydraulicInductance.second.P", "[Pa|bar]", \
"section4.compresiveVolume.P", 1, 1, 8, 4)
DeclareAlias2("section4.hydraulicInductance.second.v", "[m3/s]", \
"section4.hydraulicInductance.v", -1, 1, 9, 132)
DeclareParameter("section4.hydraulicInductance.L", "", 31, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("section4.hydraulicInductance.D", "", 32, 1.29, 0.0,0.0,0.0,0,560)
DeclareParameter("section4.hydraulicInductance.A", "", 33, 0.01, 0.0,0.0,0.0,0,560)
DeclareVariable("section4.pipeFriction.P", "[Pa|bar]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("section4.pipeFriction.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("section4.pipeFriction.first.P", "[Pa|bar]", "section4.compresiveVolume.P", 1,\
 1, 8, 4)
DeclareVariable("section4.pipeFriction.first.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,777)
DeclareAlias2("section4.pipeFriction.second.P", "[Pa|bar]", "section4.compresiveVolume.P", 1,\
 1, 8, 4)
DeclareVariable("section4.pipeFriction.second.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,777)
DeclareParameter("section4.pipeFriction.Kr", "[Pa.m-3.s]", 34, 5000, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("section4.pin1.P", "[Pa|bar]", "section4.compresiveVolume.P", 1, 1,\
 8, 1028)
DeclareVariable("section4.pin1.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,2825)
DeclareAlias2("section4.pin.P", "[Pa|bar]", "section3.pin2.P", 1, 5, 20, 4)
DeclareAlias2("section4.pin.v", "[m3/s]", "section4.hydraulicInductance.v", 1, 1,\
 9, 132)
DeclareAlias2("section4.pin2.P", "[Pa|bar]", "section4.compresiveVolume.P", 1, 1,\
 8, 4)
DeclareVariable("section4.pin2.v", "[m3/s]", 0.0, 0.0,0.0,0.0,0,777)
DeclareAlias2("signalPressure.u", "[Pa]", "section.pin.P", 1, 5, 4, 0)
DeclareAlias2("signalPressure.first.P", "[Pa|bar]", "section.pin.P", 1, 5, 4, 4)
DeclareAlias2("signalPressure.first.v", "[m3/s]", "section.hydraulicInductance.v", -1,\
 1, 1, 132)
DeclareParameter("sine.amplitude", "Amplitude of sine wave", 35, 1000, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sine.freqHz", "Frequency of sine wave [Hz]", 36, 60, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sine.phase", "Phase of sine wave [rad|deg]", 37, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sine.offset", "Offset of output signal", 38, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("sine.startTime", "Output = offset for time < startTime [s]", 39,\
 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("sine.y", "Connector of Real output signal [Pa]", "section.pin.P", 1,\
 5, 4, 0)
DeclareVariable("sine.pi", "", 3.141592653589793, 0.0,0.0,0.0,0,2561)
EndNonAlias(0)
#define NX_    10
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    29
#define NP_    40
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -587995086
#define NHash2_ -546276458
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    76
#define SizePre_ 0
#define SizeEq_ 10
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 5
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(F_[0], 0.0, 8);
DoRemember_(F_[1], 0.0, 9);
DoRemember_(F_[2], 0.0, 6);
DoRemember_(F_[3], 0.0, 7);
DoRemember_(F_[4], 0.0, 4);
DoRemember_(F_[5], 0.0, 5);
DoRemember_(F_[6], 0.0, 2);
DoRemember_(F_[7], 0.0, 3);
DoRemember_(F_[8], 0.0, 0);
DoRemember_(F_[9], 0.0, 1);
EndEqBlock
EndDataBlock
