/* Auto-generated by genmsg_cpp for file /home/diego/fuerte_workspace/sandbox/Cognitive/world/msg/is_cam_moving_msg.msg */
#ifndef WORLD_MESSAGE_IS_CAM_MOVING_MSG_H
#define WORLD_MESSAGE_IS_CAM_MOVING_MSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace world
{
template <class ContainerAllocator>
struct is_cam_moving_msg_ {
  typedef is_cam_moving_msg_<ContainerAllocator> Type;

  is_cam_moving_msg_()
  : cam_state(false)
  {
  }

  is_cam_moving_msg_(const ContainerAllocator& _alloc)
  : cam_state(false)
  {
  }

  typedef uint8_t _cam_state_type;
  uint8_t cam_state;


  typedef boost::shared_ptr< ::world::is_cam_moving_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world::is_cam_moving_msg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct is_cam_moving_msg
typedef  ::world::is_cam_moving_msg_<std::allocator<void> > is_cam_moving_msg;

typedef boost::shared_ptr< ::world::is_cam_moving_msg> is_cam_moving_msgPtr;
typedef boost::shared_ptr< ::world::is_cam_moving_msg const> is_cam_moving_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::world::is_cam_moving_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::world::is_cam_moving_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace world

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::world::is_cam_moving_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::world::is_cam_moving_msg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::world::is_cam_moving_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4f5186cce6f51e3392e21dd852d2725e";
  }

  static const char* value(const  ::world::is_cam_moving_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4f5186cce6f51e33ULL;
  static const uint64_t static_value2 = 0x92e21dd852d2725eULL;
};

template<class ContainerAllocator>
struct DataType< ::world::is_cam_moving_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "world/is_cam_moving_msg";
  }

  static const char* value(const  ::world::is_cam_moving_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::world::is_cam_moving_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool cam_state\n\
\n\
";
  }

  static const char* value(const  ::world::is_cam_moving_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::world::is_cam_moving_msg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::world::is_cam_moving_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cam_state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct is_cam_moving_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world::is_cam_moving_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::world::is_cam_moving_msg_<ContainerAllocator> & v) 
  {
    s << indent << "cam_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cam_state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // WORLD_MESSAGE_IS_CAM_MOVING_MSG_H

