(cl:defpackage ball_detection-srv
  (:use )
  (:export
   "FIND_BALLS"
   "<FIND_BALLS-REQUEST>"
   "FIND_BALLS-REQUEST"
   "<FIND_BALLS-RESPONSE>"
   "FIND_BALLS-RESPONSE"
   "FIND_BOXES"
   "<FIND_BOXES-REQUEST>"
   "FIND_BOXES-REQUEST"
   "<FIND_BOXES-RESPONSE>"
   "FIND_BOXES-RESPONSE"
  ))

