"""autogenerated by genpy from ros_tum_msgs/CameraInfoRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CameraInfoRequest(genpy.Message):
  _md5sum = "650f0ccd41c8f8d53ada80be6ddde434"
  _type = "ros_tum_msgs/CameraInfoRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 request

"""
  __slots__ = ['request']
  _slot_types = ['int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       request

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CameraInfoRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.request is None:
        self.request = 0
    else:
      self.request = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_i.pack(self.request))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.request,) = _struct_i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_i.pack(self.request))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.request,) = _struct_i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
"""autogenerated by genpy from ros_tum_msgs/CameraInfoResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_tum_msgs.msg

class CameraInfoResponse(genpy.Message):
  _md5sum = "ac7cfdf594c124760bb3d9e47ea1f9d7"
  _type = "ros_tum_msgs/CameraInfoResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """CameraCalibData response


================================================================================
MSG: ros_tum_msgs/CameraCalibData
int32 width
int32 height
string encoding
float64[9] K
float64[16] E
float64[12] P

"""
  __slots__ = ['response']
  _slot_types = ['ros_tum_msgs/CameraCalibData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       response

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CameraInfoResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.response is None:
        self.response = ros_tum_msgs.msg.CameraCalibData()
    else:
      self.response = ros_tum_msgs.msg.CameraCalibData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.response.width, _x.response.height))
      _x = self.response.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_9d.pack(*self.response.K))
      buff.write(_struct_16d.pack(*self.response.E))
      buff.write(_struct_12d.pack(*self.response.P))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.response is None:
        self.response = ros_tum_msgs.msg.CameraCalibData()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.response.width, _x.response.height,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.response.encoding = str[start:end].decode('utf-8')
      else:
        self.response.encoding = str[start:end]
      start = end
      end += 72
      self.response.K = _struct_9d.unpack(str[start:end])
      start = end
      end += 128
      self.response.E = _struct_16d.unpack(str[start:end])
      start = end
      end += 96
      self.response.P = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.response.width, _x.response.height))
      _x = self.response.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(self.response.K.tostring())
      buff.write(self.response.E.tostring())
      buff.write(self.response.P.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.response is None:
        self.response = ros_tum_msgs.msg.CameraCalibData()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.response.width, _x.response.height,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.response.encoding = str[start:end].decode('utf-8')
      else:
        self.response.encoding = str[start:end]
      start = end
      end += 72
      self.response.K = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 128
      self.response.E = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=16)
      start = end
      end += 96
      self.response.P = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=12)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_16d = struct.Struct("<16d")
_struct_12d = struct.Struct("<12d")
_struct_2i = struct.Struct("<2i")
_struct_9d = struct.Struct("<9d")
class CameraInfo(object):
  _type          = 'ros_tum_msgs/CameraInfo'
  _md5sum = '073f070c2953c18ba992230f135fd1df'
  _request_class  = CameraInfoRequest
  _response_class = CameraInfoResponse
